[feat]: Added component for Todo page
Fucha97/wb_todo pull request #5
Opened 2023-10-01 23:15 UTC by Fucha97

2023-10-02 15:34 UTC, fowku requested changes

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/index.tsx
> +    <ConnectedWrapper />
надо дать осмысленное название для компонента, если у тебя есть TodosView, компонент, в котором описана логика и есть подключение к стору должен называться ConnectedTodos

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/index.tsx
> +export const TodosView = memo(
это должен быть ConnectedTodos, потому что есть подключение к стору. View компоненты ничего про стор не знают и получают значения из пропсов – их стараемся делать максимально тупыми, чисто для отображения данных. Connected компоненты реализуют логику

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +export const UpdateTodoModal = ({
та же история, надо разбить на Connected и View компонент

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.module.scss
> +    background-color: $White;
это deprecated цвета, используй из /styles/pallete, реэкспортятся в /constants

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const [newTodoTitle, setNewTodoTitle] = useState<string>('');
в целом можно не указывать тип, если при ините указана строка, но так тоже норм

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const [newTodoDescription, setNewTodoDescription] = useState<string>('');
я бы форму склеил в один стейт, иначе дальше оно будет разростаться в кучу стейтов и хэндлеров, которые можно объединить в один дженерик

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const handleChangeNewTodoDescription: SimpleInputPropsType['onChange'] = ({
к коменту выше, после объединения в общий стейт можно будет избавиться от этого хендлера, и хэндлера для тайтла

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const handleTodoCreate: (event?: ButtonClickEventType) => void = () => {
немного странная анотация для функции, кажется что можно не указывать тип для переменной, а описывать в самой стрелочной функции что она принимает, и что должна отдать

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +      <div className={cn(`${BLOCK_NAME}__inputs_wrapper`)}>
по БЭМу есть договоренность, что для модификаторов используем --, а не _. но тут похоже, что подразумевался просто элемент

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +          name="add-todo-item"
может вынести в константу?

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +          id="add-todo-item"
у тебя id дублируются с вышестоящим инпутом

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +        text="Add"
тут перевода не хватает

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +        disabled={todoCreateDisabled || loading}
кажется, что если у кнопки есть loading, то ее не нужно отключать

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +  ...todoProps
по этой теме был холивар, что мы пропсы так не спрэдим, а явно пишем

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +  const handlerUpdateTodoClick: (event: ButtonClickEventType) => void = () => {
та же история с аннтоацией, кажется, что она тут вообще не нужна

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +  ) => void = () => {
и тут аннотация

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +          text="Update"
перевода не хватает

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +          text="Delete"
перевода не хватает

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/todoList/index.tsx
> +export const TodoList = ({
тут тоже нужно разбить на Connected и View

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +        id="update-todo-item"
тут тоже id дублируются

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +  const handleChangeTodoTitle: SimpleInputPropsType['onChange'] = ({
тут можно в одну дженерик функцию эти хэндлеры свернуть

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +        title: 'Save',
тут тоже переводов не хватает

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +        variant: 'accent' as ButtonVariant,
мб для `actionsConfig` задать тип, который принимает модалка, чтобы assertions не писать?

2023-10-02 15:34 UTC, fowku commented on src/pages/todos/page/_components/todosView/index.tsx
> +  updateTodoData: ReturnType<typeof selectUpdateTodo>;
во вьюшки actions я бы не пробрасывал, но это должно исправиться когда разобьешь на View и Connected компоненты

2023-10-03 13:24 UTC, Fucha97 commented on src/pages/todos/page/index.tsx
> +    <ConnectedWrapper />
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/index.tsx
> +export const TodosView = memo(
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +export const UpdateTodoModal = ({
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.module.scss
> +    background-color: $White;
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +        id="update-todo-item"
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +  const handleChangeTodoTitle: SimpleInputPropsType['onChange'] = ({
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +        title: 'Save',
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/updateTodoModal/index.tsx
> +        variant: 'accent' as ButtonVariant,
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/index.tsx
> +  updateTodoData: ReturnType<typeof selectUpdateTodo>;
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/todoList/index.tsx
> +export const TodoList = ({
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +          text="Delete"
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +          text="Update"
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +  ) => void = () => {
Fixed

2023-10-03 13:25 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +  const handlerUpdateTodoClick: (event: ButtonClickEventType) => void = () => {
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/todoCard/index.tsx
> +  ...todoProps
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +        disabled={todoCreateDisabled || loading}
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +        text="Add"
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +          id="add-todo-item"
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +      <div className={cn(`${BLOCK_NAME}__inputs_wrapper`)}>
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const handleTodoCreate: (event?: ButtonClickEventType) => void = () => {
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const handleChangeNewTodoDescription: SimpleInputPropsType['onChange'] = ({
Fixed

2023-10-03 13:31 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/newTodoForm/index.tsx
> +  const [newTodoDescription, setNewTodoDescription] = useState<string>('');
Fixed

2023-10-03 14:46 UTC, fowku requested changes

2023-10-03 14:46 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedTodoList/todoListView/index.tsx
> +  deleteTodo: typeof deleteTodoActionSaga;
избавься от редакса в этом компоненте, запили ивенты вместо этих пропсов. напривер deleteTodo -> onDeleteTodo

2023-10-03 14:46 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +  }, [updateTodoData]);
нужно ли тебе апдейтить данные в модалке во время редактирования карточки? кажется, что при маунте достаточно в стейт сетить, инфа не должна сама меняться, пока ты редактируешь каррточку

2023-10-03 14:46 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +const mapStateToProps = (state: TodoStorageStateType) => ({
типизируй это и `mapDispatchToProps`, пропсы компонента надо запилить в стиле `type TPropsType = TMapStateToProps & TMapDispatchToProps`

2023-10-03 14:46 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/updateTodoModal/index.tsx
> +  isModalOpen: ReturnType<typeof selectUpdateTodoModalOpen>;
тут тоже от редаксовских типов избавься

2023-10-03 14:46 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/updateTodoModal/index.tsx
> +    title="Update todo"
перевод пропустил

2023-10-03 15:09 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +  const handlerChangeTodo = (property: string, value: string) => {
тупо что TS не ругнулся на типы, такая конструкция тебя защитит от нежелательных записей в стейт `const handlerChangeTodo = <Key extends keyof TodoType>(
    property: Key,
    value: TodoType[Key],
  )`

2023-10-03 15:11 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +    const currentProperty = splitedName[splitedName.length - 1];
вот эта история совсем не нравится, лучше два отдельных хэндлера написать, где будет явно вызываться handlerChangeTodo('property', value)

2023-10-03 15:14 UTC, fowku commented on src/pages/todos/page/_components/todosView/components/connectedTodoList/todoListView/todoCard/index.tsx
> +            text={`Created date: ${createdAt}`}
надо переводом запилить

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedTodoList/todoListView/index.tsx
> +  deleteTodo: typeof deleteTodoActionSaga;
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +  }, [updateTodoData]);
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +const mapStateToProps = (state: TodoStorageStateType) => ({
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/updateTodoModal/index.tsx
> +  isModalOpen: ReturnType<typeof selectUpdateTodoModalOpen>;
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/updateTodoModal/index.tsx
> +    title="Update todo"
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +  const handlerChangeTodo = (property: string, value: string) => {
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedUpdateTodoModal/index.tsx
> +    const currentProperty = splitedName[splitedName.length - 1];
Fixed

2023-10-03 23:57 UTC, Fucha97 commented on src/pages/todos/page/_components/todosView/components/connectedTodoList/todoListView/todoCard/index.tsx
> +            text={`Created date: ${createdAt}`}
Fixed

2023-10-04 10:06 UTC, merged